batch_size: 128
seq_len: 100
predict_len: 0
label_len: 0
do_eval: True
epoch: 1
training: True 
anomaly_ratio: 1
task: anomaly


dataset: 
  name: TSADDataset
  dataset_root: ../data/
  # train_path: ../data/swat_train.csv
  # val_path: ../data/swat_test.csv
  # train_path: ../data/psm_train.csv
  # val_path: ../data/psm_test.csv
  train_path: ../data/MSL_train.csv
  val_path: ../data/MSL_test.csv

  scale: True
  time_feat: False

info_params:
  # freq: 1
  # label_col: "Normal/Attack"
  # feature_cols: ['FIT101', 'LIT101', ' MV101', 'P101', 'P102', ' AIT201', 'AIT202', 
  #           'AIT203', 'FIT201', ' MV201', ' P201', ' P202', 'P203', ' P204',
  #           'P205', 'P206', 'DPIT301', 'FIT301', 'LIT301', 'MV301', 'MV302',
  #           ' MV303', 'MV304', 'P301', 'P302', 'AIT401', 'AIT402', 'FIT401',
  #           'LIT401', 'P401', 'P402', 'P403', 'P404', 'UV401', 'AIT501',
  #           'AIT502', 'AIT503', 'AIT504', 'FIT501', 'FIT502', 'FIT503',
  #           'FIT504', 'P501', 'P502', 'PIT501', 'PIT502', 'PIT503', 'FIT601',
  #           'P601', 'P602', 'P603']

  # freq: 1
  # label_col: label
  # time_col: timestamp
  # feature_cols: ['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24']

  freq: 1
  label_col: label
  feature_cols: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54']



model: 
  name: PP-TS-AD
  model_cfg:
    Ensemble:
      TimesNet_AD: configs/anomaly/anomaly_base.yaml
      RLinear_AD: configs/anomaly/rlinear_anomaly.yaml
      DLinear_AD: configs/anomaly/dlinear_anomaly.yaml
      NLinear_AD: configs/anomaly/nlinear_anomaly.yaml
      PatchTST_AD: configs/anomaly/patchtst_anomaly.yaml
      NonStationary_AD: configs/anomaly/non_stationary_ad.yaml
      AutoEncoder: configs/anomaly/autoencoder_anomaly.yaml
    optimizer_params:
      learning_rate: 0.001
      gamma: 0.5

loss: mse

test:
  stride: 1 

output: 'output/'