batch_size: 128
seq_len: 100
predict_len: 0
label_len: 0
do_eval: True
epoch: 1
training: True 
eval_metrics: ["mae", "mse"] 
anomaly_ratio: 1

lr_scheduler: 
  name: Type1Decay
  lr_cfg:
    learning_rate: 0.001
    last_epoch: 0

dataset: 
  name: MSL

model: 
  name: TimesNetModel
  model_cfg:
    task_name: anomaly_detection
    enc_in: 55
    c_out: 55
    e_layers: 1
    num_kernels: 6
    d_model: 8
    d_ff: 16
    add_transformed_datastamp: False 
    need_date_in_network: False 
    top_k: 3 
    window_sampling_limit: Null 
    renorm: Null 
    drop_last: False

loss: mse

test:
  stride: 1 

output: 'output/'
