batch_size: 128 #
seq_len: 100 #
predict_len: 0 #
label_len: 0 #
do_eval: True #
epoch: 10 # max_epochs
training: True # 
eval_metrics: ["mae", "mse"] # 
anomaly_ratio: 0.5

lr_scheduler: # 
  name: Type1Decay
  lr_cfg:
    learning_rate: 0.001
    last_epoch: 0

dataset: 
  name: SMD

model: 
  name: TimesNetModel
  model_cfg:
    task_name: anomaly_detection
    enc_in: 38 #
    c_out: 38 #
    e_layers: 2 #
    num_kernels: 6 #
    d_model: 64 #
    d_ff: 64 #
    add_transformed_datastamp: True # 
    need_date_in_network: False # 
    top_k: 3 # 
    window_sampling_limit: Null # 
    renorm: Null # 
    drop_last: False #

loss: mse # or smape or CE

test:
  stride: 1 # 

output: 'output/'