batch_size: 16 #
seq_len: 28 #
predict_len: 14 #
label_len: 14 #
do_eval: True #
epoch: 10 # max_epochs
training: True # 
eval_metrics: ['smape'] # 
anomaly_ratio: Null

lr_scheduler: # 
  name: Type1Decay
  lr_cfg:
    learning_rate: 0.001
    last_epoch: 0

dataset: 
  name: M4Daily

model: 
  name: TimesNetModel
  model_cfg:
    task_name: short_term_forecast
    enc_in: 1 #
    c_out: 1 #
    e_layers: 2 #
    num_kernels: 6 #
    d_model: 16 #
    d_ff: 16 #
    add_transformed_datastamp: False # 
    need_date_in_network: False # 
    top_k: 5 # 
    window_sampling_limit: 140 # 
    renorm: Null # 
    drop_last: False #

loss: smape # or smape or CE

test:
  stride: 1 # 

output: 'output/'