batch_size: 32
seq_len: 672
predict_len: 24
do_eval: True
epoch: 20


dataset: 
  name: ETTm1
  split:
    train: [0, 34560]  # 12 * 30 * 24
    val: [34560, 46080]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [46080, 57600] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]


model: 
  name: Crossformer
  model_cfg:
    c_in: 7
    win_size: 2
    factor: 10
    dropout: 0.2
    seg_len: 12
    d_model: 256 
    d_ff: 512
    n_heads: 4
    e_layers: 3
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.7
    patience: 3
    #pretrain: Crossformer_init_etth1.pdparams

test:
  stride: 1

  



