batch_size: 32
seq_len: 96
predict_len: 96
do_eval: True
sampling_stride: 1
epoch: 5


dataset: 
  name: Dataset
  dataset_root: /data/
  train_path: /data/train.csv
  val_path: /data/val.csv
  time_feat: True
  scale: True

info_params:
  time_col: date

model: 
  name: Nonstationary_Transformer
  model_cfg:
    c_in: 321
    factor: 3
    p_hidden_dims: [256, 256]
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.5
    patience: 5
    #pretrain: non-station_torch.pdparams

test:
  stride: 1

  



