batch_size: 32
seq_len: 96
predict_len: 720
do_eval: True
epoch: 10


dataset: 
  name: Weather
  split:
    train: [0, 36887]  # 0.7
    val: [36887, 42157]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [42157, 52696] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]


model: 
  name: Nonstationary_Transformer
  model_cfg:
    c_in: 21
    factor: 3
    p_hidden_dims: [128, 128]
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.5
    patience: 5
    #pretrain: non-station_torch.pdparams

test:
  stride: 1

  



