batch_size: 32
seq_len: 36
predict_len: 36
do_eval: True
epoch: 10


dataset: 
  name: ILI
  split:
    train: [0, 676]  # 12 * 30 * 24
    val: [676, 773]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [773, 966] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]
  

model: 
  name: Nonstationary_Transformer
  model_cfg:
    c_in: 7
    factor: 3
    label_len: 18
    p_hidden_dims: [16, 16]
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.5
    patience: 3
    #pretrain: non_init_ill_36.pdparams

test:
  stride: 1

  



