batch_size: 16
seq_len: 36
predict_len: 36
do_eval: True
epoch: 100


dataset: 
  name: ILI
  split:
    train: [0, 676]  # 12 * 30 * 24
    val: [676, 773]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [773, 966] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]


model: 
  name: PatchTSTModel
  model_cfg:
    c_in: 7
    n_layers: 3
    n_heads: 4
    d_model: 16
    d_ff: 128
    dropout: 0.3
    fc_dropout: 0.3
    head_dropout: 0.0
    patch_len: 24
    stride: 2
    patience: 100
    optimizer_params:
      learning_rate: 0.0025
    #pretrain: patchtst_init_param_ill.pdparams
    
test:
  stride: 1

  



