batch_size: 128
seq_len: 96
predict_len: 720
do_eval: True
epoch: 15


dataset: 
  name: ETTm1
  split:
    train: [0, 34560]  # 12 * 30 * 24
    val: [34560, 46080]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [46080, 57600] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]


model: 
  name: RLinearModel
  model_cfg:
    c_in: 7
    dropout: 0.1
    optimizer_params:
      learning_rate: 0.005
      gamma: 0.5
    patience: 10

test:
  stride: 1

  



