batch_size: 1
seq_len: 96
predict_len: 720
do_eval: True
epoch: 50


dataset: 
  name: Weather
  split:
    train: [0, 36887]  # 0.7
    val: [36887, 42157]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [42157, 52696] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]
  use_holiday: False

model: 
  name: TiDE
  model_cfg:
    c_in: 21
    num_encoder_layers: 1
    use_revin: False
    drop_prob: 0.0
    hidden_size: 512
    decoder_output_dim: 8
    temporal_decoder_hidden: 16
    optimizer_params:
      learning_rate: 0.00003
      gamma: 0.5
    patience: 10
    #pretrain: non-station_torch.pdparams

test:
  stride: 1

  



