batch_size: 32 #
seq_len: 36 #
predict_len: 24 #
label_len: 0 #
do_eval: True #
epoch: 10 # max_epochs
training: True # 
eval_metrics: ["mae", "mse"] # 
anomaly_ratio: Null

lr_scheduler: # 
  name: Type1Decay
  lr_cfg:
    learning_rate: 0.0001
    last_epoch: 0

dataset: 
  name: ILI
  split:
    train: [0, 676]  # 12 * 30 * 24
    val: [676, 773]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [773, 966] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]


model: 
  name: TimesNetModel
  model_cfg:
    task_name: long_term_forecast
    enc_in: 7 #
    c_out: 7 #
    e_layers: 2 #
    num_kernels: 6 #
    d_model: 768 #
    d_ff: 768 #
    add_transformed_datastamp: True # 
    need_date_in_network: True # 
    top_k: 5 # 
    window_sampling_limit: Null # 
    renorm: Null # 
    drop_last: False #

Loss: mse # or smape or CE

test:
  stride: 1 # 

output: 'output/'