batch_size: 32 #
seq_len: 96 #
predict_len: 96 #
do_eval: True #
epoch: 10 # max_epochs 


dataset: 
  name: ETTh1
  split:
    train: [0, 8640]  # 12 * 30 * 24
    val: [8640, 11520]  # [12 * 30 * 24 - seq_len, 12 * 30 * 24 + 4 * 30 * 24]
    test: [11520, 14400] # [12 * 30 * 24 + 4 * 30 * 24 - seq_len, 12 * 30 * 24 + 8 * 30 * 24]


model: 
  name: TimesNetModel
  model_cfg:
    c_in: 7 #
    c_out: 7 #
    e_layers: 2 #
    num_kernels: 6 #
    d_model: 16 #
    d_ff: 32 #
    top_k: 5 # 
    renorm: Null # 
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.5

test:
  stride: 1 # 