batch_size: 32 #
seq_len: 96 #
predict_len: 96 #
do_eval: True #
epoch: 10 # max_epochs


dataset: 
  name: ETTm2
  split:
    train: [0, 34560]  # 12 * 30 * 24 * 4
    val: [34560, 46080]  # [12 * 30 * 24 * 4 - seq_len, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4]
    test: [46080, 57600] # [12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - seq_len, 12 * 30 * 24 * 4 + 8 * 30 * 24 * 4]


model: 
  name: TimesNetModel
  model_cfg:
    c_in: 7 #
    c_out: 7 #
    e_layers: 2 #
    num_kernels: 6 #
    d_model: 32 #
    d_ff: 32 #
    top_k: 5 # 
    renorm: Null # 
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.5

test:
  stride: 1 # 
